### ISSUE TITLE
convert to python3.x

### ISSUE THREAD

**Issue by mmckerns** [uqfoundation/pyina#1]
convert to python3.x

**Comment by jacobic** [comment]
Pyina would be absolutely amazing if it was python3 compatible, has there been any progress in porting it since this issue was opened?

**Comment by mmckerns** [comment]
@jacobic: It's on my short list of things to do next.  I have some need to update this package in the coming months, so hopefully it will get some attention and get converted during that time.

**Comment by LeeKamentsky** [comment]
I'm looking at pyina - it is exactly what I need, but I'm on Python 3.6. I'm trying to make quick work of the conversions to 3.x. Would you take a pull request when I'm done? (it will be a bit of a nightmare, I'm touching all your files)
