### ISSUE TITLE
ensure install works with pip

### ISSUE THREAD

**Issue by mmckerns** [uqfoundation/pyina#16]
Migrated from: http://trac.mystic.cacr.caltech.edu/project/pathos/ticket/164 (split with `pathos`)

**Comment by uber1geek** [comment]
have you tried installing as root ? sudo pip install

**Comment by mmckerns** [comment]
Looks like I neglected to close this ticket.

`pyina` should install with `pip install git+https://github.com/uqfoundation/pyina` as of https://github.com/uqfoundation/pathos/commit/133b469495ae5e94d089dee1bb1e44637fac33b1.  The issue for a `pip` install was a failure to install the dependency on `pathos`.
